### PR TITLE
add support for config file

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
Hmm.. I'm not sure why those extra commits showed up. I'll fix it if I can

**Comment by andy5995** [comment]
Fixed.

**Comment by erichoog** [comment]
Thanks @andy5995! I'll test this out later today but I'm sure I'll merge it.  Looks good!

**Comment by erichoog** [comment]
@andy5995 great idea!  I'll likely split this into two functions mainly becuase I want the script config section to be in it's own function and very easy for someone to find.  It'll still work the same though!

**Comment by andy5995** [comment]
Sounds like a plan!

**Pull request merged**
